### PR TITLE
Add JuliaFormatter

### LINKED ISSUE #214: Add JuliaFormatter

### PR DESCRIPTION
**Pull request by odow**
Closes #214

### CODE REVIEW

**Comment by kalmarek** [comment]
@odow which IDE are you using? or is there an easy way to set this up with vscode? (given that atom is semi-maintained)?

**Comment by odow** [comment]
https://jump.dev/JuMP.jl/stable/developers/style/#JuliaFormatter

**Comment by odow** [comment]
@kalmarek @blegat I'm in favor of merging this ASAP. 

The downside is that it will require the current PRs to be rebased. But I can do that since I'll be the one breaking them.

It also shouldn't be too hard. The workflow would be

 * Run JuliaFormatter on the PR.
 * Squash all of the commits into a single commit
 * Rebase on `master`

**Comment by kalmarek** [comment]
I won't be able to work on SCS for the next two weeks, so go ahead!

**Pull request merged**
