### PR TITLE
update to scs-3.0.0

### PR DESCRIPTION
**Pull request by kalmarek**
a few problems:

* when warmstarting, setting `p,d,s` works just fine, but unless a number of iterations is allowed (`151` in the default settings) objective becomes `nan` (already in scs). This may explain some of the test errors; This seems to be a problem with `scs` itself @bodono 
* `feasible_exponential_conic(...)` and `feasible_sdp_conic(...)` from `test/test_problems.jl` fail with numerous warnings `warning: exp cone newton step hit maximum 100 iters`. This is probably an issue with current branch; I'll investigate.

In general this reaches test status
```julia
Test Summary:                                             | Pass  Fail  Total
SCS                                                       | 5240    74   5314
```
with `4` `feasible_*` failures and the same `33` failures for each of `SCS.DirectSolver` and `SCS.IndirectSolver`:
```julia
  MOI wrapper: SCS.DirectSolver                           | 2390    33   2423
    SolverName                                            |    1            1
    Unit                                                  |  348          348
    Continuous linear problems with SCS.DirectSolver      |  478    18    496
      linear8a                                            |   13           13
      linear14                                            |   40           40
      linear6                                             |   34           34
      linear4                                             |   24           24
      linear3                                             |   28           28
      linear9                                             |   13     2     15
      linear8c                                            |   13           13
      linear1                                             |  120          120
      linear2                                             |   24           24
      partial_start                                       |    1     5      6
      linear12                                            |   17           17
      linear7                                             |   22           22
      linear8b                                            |   12           12
      linear10b                                           |   18           18
      linear10                                            |   27    11     38
      linear15                                            |   12           12
      linear5                                             |   28           28
      linear13                                            |   16           16
      linear11                                            |   16           16
    ADMMIterations attribute with SCS.DirectSolver        |  121          121
    Continuous quadratic problems with SCS.DirectSolver   |   87     8     95
      qcp1                                                |   12     8     20
      qcp3                                                |   17           17
      qcp4                                                |   21           21
      qcp5                                                |   21           21
      qcp2                                                |   16           16
    Continuous conic problems with SCS.DirectSolver       | 1355     7   1362
      norminf                                             |   89           89
      normone                                             |   88           88
      sdp                                                 |  237          237
      normnuc                                             |   30           30
      dualexp                                             |   50           50
      dualpow                                             |   48           48
      exp                                                 |   97           97
      lin                                                 |  135          135
      logdet                                              |   72           72
      soc                                                 |  131          131
      normspec                                            |   30           30
      rootdet                                             |   54     7     61
        rootdett                                          |   54     7     61
          rootdett1v                                      |   23           23
          rootdett1f                                      |   23           23
          rootdett2                                       |    8     7     15
      relentr                                             |   15           15
      rsoc                                                |  129          129
      pow                                                 |   42           42
      geomean                                             |  108          108
```

### CODE REVIEW

**Comment by bodono** [comment]
What is `p,d,s`? I don't understand what is meant by 'unless a number of iterations is allowed', do you mean unless `max_iters > 0`?

I don't use Julia - Is there an easy way for me to install a virtual Julia env, pull this down and test it? Alternatively you can send me the data from failing tests and I can investigate that way. If you pass `write_data_filename' to SCS when you are calling it will dump a data file that I can read in.

**Comment by kalmarek** [comment]
@bodono Sorry for my abbreviations:
setting values for `primal`, `dual` and `slack` works fine (I can see this by observing the residuals etc at `0` iteration of `scs`).

Now I think that the issue with `warm_start` was a red herring. What happens actually is that setting `max_iters` too low (e.g. `200`) so that SCS reaches `hit max_iters` results in `objective = nan` even on the `scs` side. e.g. here SCS needs 300(?) iterations to solve this problem, bu setting `max_iters=300` results in

```julia
    A = [1.0 1.0 0.0 0.0 0.0;
        0.0 1.0 0.0 0.0 1.0;
        0.0 0.0 1.0 1.0 1.0]
    collb = [0.0, 0.0, 0.0, 0.0, 0.0]
    obj   = [3.0, 4.0, 4.0, 9.0, 5.0]
    rowub = [ 5.0,  3.0,  9.0]
    
    s = SCSSolver(max_iters=300)
    m = MathProgBase.ConicModel(s)
    MathProgBase.loadproblem!(m, -obj, A, rowub, [(:NonNeg,1:3)],[(:NonNeg,1:5)])
    MathProgBase.optimize!(m)
```
results with
```
------------------------------------------------------------------
               SCS v3.0.0 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 5, constraints m: 8
cones:    l: linear vars: 8
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
          alpha: 1.50, scale: 1.00e-01, adaptive_scaling: 1
          max_iters: 300, normalize: 1, warm_start: 0
lin-sys:  sparse-direct
          nnz(A): 12, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 6.47e+01  8.41e+00  5.53e+02 -5.72e+02  1.00e-01  9.55e-05 
   250| 4.62e-03  4.36e-05  3.84e-03 -9.90e+01  1.00e-01  2.10e-03 
   300| 1.65e-04  1.42e-04  8.39e-05 -9.90e+01  1.00e-01  2.50e-03 
------------------------------------------------------------------
status:  hit max_iters
timings: total: 2.60e-03s = setup: 9.06e-05s + solve: 2.50e-03s
         lin-sys: 4.27e-04s, cones: 3.68e-04s, accel: 3.60e-04s
lin-sys: nnz(L): 25
------------------------------------------------------------------
------------------------------------------------------------------
objective = nan
------------------------------------------------------------------
```
on the other hand with `max_iters=301` I get
```
------------------------------------------------------------------
               SCS v3.0.0 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 5, constraints m: 8
cones:    l: linear vars: 8
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
          alpha: 1.50, scale: 1.00e-01, adaptive_scaling: 1
          max_iters: 301, normalize: 1, warm_start: 0
lin-sys:  sparse-direct
          nnz(A): 12, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 6.47e+01  8.41e+00  5.53e+02 -5.72e+02  1.00e-01  1.03e-04 
   250| 4.62e-03  4.36e-05  3.84e-03 -9.90e+01  1.00e-01  2.37e-03 
   300| 3.34e-04  1.33e-04  3.04e-04 -9.90e+01  1.00e-01  2.82e-03 
------------------------------------------------------------------
status:  solved
timings: total: 2.95e-03s = setup: 1.21e-04s + solve: 2.83e-03s
         lin-sys: 5.11e-04s, cones: 4.46e-04s, accel: 4.02e-04s
lin-sys: nnz(L): 25
------------------------------------------------------------------
cones: dist(s, K) = 0.00e+00, dist(y, K*) = 0.00e+00
comp slack: s'y/|s||y| = 0.00e+00, gap: |x'Px+c'x+b'y| = 3.04e-04
pri res: |Ax+s-b| = 3.34e-04, dua res: |Px+A'y+c| = 1.33e-04
------------------------------------------------------------------
objective = -99.000837
------------------------------------------------------------------
```

If that's not enough to reproduce it on SCS side I'll prepare detailed instructions for reproducing, please let me know!

**Comment by bodono** [comment]
Thanks, I can dig in with that. I'm more concerned with the exponential cone warnings though, can you send me the data for a problem that has that issue?

**Comment by kalmarek** [comment]
sure! the exponential cone problem data in very scs form can be found here: https://github.com/jump-dev/SCS.jl/blob/500e75d8f3a3467b8ae2814a49e41aa05c31439e/test/test_problems.jl#L439
(this `scs_solve` there resolves almost directly to calling `scs` library)

just below there is also the definition of sdp problem which has similar issues.

**Comment by bodono** [comment]
Great thanks, I will take a look!

**Comment by bodono** [comment]
I translated to python and I don't get those warnings. When I print out the number of exp cone steps I don't see more than about 12. I will try the sdp one now. I suppose the difference might be that we're testing at different commits of the 3.0.0 branch. I just tested at HEAD (8bfba8c66cefa1db42998e1d52bd7417b62a6d63).

```python
import scs
import numpy as np
import scipy

n = 24
m = 71
f = 10
l = 10
ep = 10
ed = 5
q = [0,1,0,2,3]

b = np.array([
-0.883995908378185202,  0.247092008779755457,  0.000000000000000000,
-0.908862166109580594,  0.493908919902298627,  0.215008446366246719,
-0.756619621167477718, -0.244711519515723036, -2.185656700286640941,
-1.777454077348217920,  1.191220488872941186, -0.072631913036035556,
-0.884888299606113149, -3.097264426296667761, -0.491714244502094944,
 0.820612279439398518, -5.027612089838516596, -0.218768971520485273,
-1.779020210515877221,  0.000000000000000000,  1.049908711514835780,
 0.423746551400514093, -0.078381703192688112, -0.387520318558316479,
 0.959884766721948446, -0.080140759738691447,  1.300716537987696597,
-0.217623259095584554, -0.772345449741623336, -0.014345948596158398,
 2.002325668310177775,  2.019795133016943467,  1.285967533112210681,
-0.503689333815666940,  3.004968290408826626, -1.438380292815098382,
-0.801360722211995502,  0.731209144814713885, -2.639460367287462361,
 1.255602400085220394, -0.301008710647552635,  0.478491654540030953,
-0.984259121708334739,  0.276318763804415002,  0.631004508865874447,
 1.808914085971600416,  0.379215625232032671, -0.627707287528726510,
-1.823589846592805763,  0.000000000000000000,  0.376255266738256766,
 0.577717062577191354,  1.119478389802739615,  0.977520182221270906,
 0.000000000000000000,  3.417141674635829851, -0.093825387556597556,
-1.780472058822893722,  1.589707484189159858,  0.133747881756402398,
 1.316803247114450848, -0.153152367127352751, -1.712195041092097192,
-0.151457896071195447,  1.216498217552836492,  0.610011299767568738,
 4.095401319683990238, -0.761957853948331154, -0.485158172250699793,
-1.990510613776122817,  1.151843011380725867])

c = np.array([
 1.126284961639569149,  0.474697659805094763, -2.123033959497108825,
 4.908405709073863754,  1.205680866991396316, -0.305211910012288978,
-6.293810724494532494, -0.698794364791622713,  2.279737335846038437,
-0.945550079347313055, -0.727867522608193762, -1.869349988323733891,
-3.748045451887451307,  1.125456539838578518,  0.750188573436658457,
 1.255406629974515686, -4.887321053728165055,  4.021564105931883404,
 0.000000000000000000, -5.091850958321861853, -0.068986990722853969,
-1.715673120575787136,  0.036366854219751360, -3.625427280331933400])

colptr = [0, 7, 12, 18, 24, 34, 37, 43, 47, 54, 59, 68, 79, 87, 93, 101,
111, 119, 127, 128, 139, 141, 150, 154, 162]

rowval = [
 5, 17, 22, 31, 55, 65, 69, 12, 18, 30, 34, 58,  9, 11, 13, 18, 30, 66,  0,
10, 17, 18, 44, 58,  5,  6,  7, 26, 29, 31, 53, 57, 61, 67, 39, 43, 68,  3,
 9, 13, 14, 16, 21,  7, 36, 38, 55,  4, 12, 21, 27, 40, 46, 66,  3, 26, 34,
44, 53,  5, 11, 17, 27, 31, 37, 42, 45, 63, 13, 22, 24, 33, 36, 40, 50, 56,
58, 64, 65,  6, 10, 13, 16, 18, 23, 41, 44, 17, 31, 41, 46, 55, 58, 16, 20,
33, 38, 42, 58, 62, 64,  7, 13, 18, 21, 26, 36, 45, 52, 56, 60,  8, 15, 21,
30, 33, 48, 53, 64,  1,  5, 11, 16, 23, 24, 28, 39, 37,  5,  8, 28, 30, 41,
55, 57, 59, 61, 64, 67, 56, 70,  0,  3, 10, 18, 22, 34, 37, 42, 65, 16, 25,
51, 65,  5, 13, 24, 28, 32, 36, 40, 55]
values = [
 0.155488995903893978, -0.062791225718324961, -0.723631125289072807,
-0.238301504589733010, -1.222593380186629552,  0.176577794642316321,
 0.705885019349415832, -1.327043149520291010, -0.054886129988677361,
 0.595357673884101768, -0.608557444738319409, -0.345065971567320995,
 0.312023828329273611,  0.600142508808629960,  0.401844497039814952,
-1.118732002452724972,  1.046832784305231856,  2.003390610862264776,
-0.289963040800027938, -0.723121479570418058, -2.021958930051789505,
-0.626378538867138679,  1.223062551733806957,  1.012801864262980134,
 0.818551368521000522, -0.493009815316450606,  0.045841105713705040,
 0.571247629714476068, -0.131820352915893585,  0.229596893220313791,
 0.245804851893843240, -0.300111005615675885, -0.438141355602143678,
-0.432003843727780446,  2.787335227813435345,  1.778255899291004472,
-0.360076301153971601,  1.174116751493714972,  1.804493771724186901,
 1.470201280848519421,  0.397466995795308642,  1.516266896645952711,
 1.808862620519253950, -0.063783120022332648,  0.910482579647111989,
 0.439952188872439920,  0.316500360797716096, -1.481399071578779925,
-1.441013597638914456, -1.079866250738828137,  0.759568325914783404,
-1.854299082689693901,  0.066756911436865754,  0.950993499549085408,
 0.126947068043645916,  0.412796010311391848, -0.737059771697805455,
-1.283256104604766579,  0.070045209416807905, -0.292588130834394000,
 0.593930795648752730, -0.982131525779047831, -0.657201299098350344,
 0.439997904822629349,  0.183703423091249041,  0.541334435719376117,
 0.901931466951714444, -0.297697144009373027, -0.326814228785906158,
-0.593250315010803608, -0.373070658631004248,  0.601102032468295078,
 0.867082552947325391, -1.140681144669632330, -0.069214254022048366,
-0.418903195029848852,  0.629334584931418806,  1.143678910770957513,
 0.970737823554688517, -0.180739356415037467,  0.526547037749559022,
 0.812323004640795987, -0.032566509194480744,  0.249517740562795132,
 0.942133319236942435, -0.433609296474823602, -2.328954516283341825,
 0.612511298166949270, -0.616865928889227422, -0.168469878275448348,
 0.035479485837577006, -1.342869236621930140, -0.213015082641054704,
 1.635999657278292441, -0.640709506726057532,  0.092307951238962266,
 0.101662443700341151,  0.389266203843263880, -0.865697308360523721,
 0.983545235205556256, -0.531620117507069279,  0.611335194065235954,
 0.545540103526115816, -0.993019006549600625,  0.199189444075264455,
-0.986961883351521907, -0.079892839058037096, -1.835638683735192345,
 0.235809672576244050, -0.140321722056366061, -0.270068812648098844,
 0.109317693774870342, -0.751894738681891606, -1.521026561768954677,
-0.197958632611841989,  1.729841391572364273,  2.227168078167871546,
-0.608580510079949288,  0.972565728008653152,  0.475424811707271355,
-0.540786416488525767, -2.186021612748235476, -0.425058490610030815,
 0.300485967595730263,  0.815488508092498399, -0.603918481376169214,
-1.166665030194641073,  0.290790134884453599, -0.308641815280113085,
 1.814015450280375585,  0.176946822329411252,  0.327678163907200726,
-0.218533560026580531, -1.032184344072171189,  1.029365712103099240,
-1.043108301337626775, -0.408674314796325655, -0.522250484993548869,
 0.648940737363586706,  0.899822328897223467,  1.415849068436585423,
 1.261550718141148275, -0.656815928948082495, -0.260250861706116776,
 0.974950224811311550,  0.401336339818801069, -1.749879306387625455,
 0.112944717021051230,  0.751228984688332879, -0.413972274974230170,
 0.589433366718220664,  0.120205281956355367, -0.507323064614498387,
-0.438270518204901538, -1.096593301525472075, -1.051632309520848407,
 0.798886992156715880, -0.307503469862750567,  0.274836786911666187,
 0.898475989377141793, -1.093343456239604494,  1.331215885064973348]

A = scipy.sparse.csc_matrix((values, rowval, colptr), shape=(m, n))

data = {'A':A, 'b':b, 'c':c}
cone = {'f':f, 'l':l, 'ep':ep, 'ed':ed, 'q':q}

sol = scs.solve(data, cone, max_iters=1000)

```

```
=> python test_bad_probs.py
------------------------------------------------------------------
	       SCS v3.0.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 24, constraints m: 71
cones: 	  f: primal zero / dual free vars: 10
	  l: linear vars: 10
	  q: soc vars: 6, soc blks: 5
	  e: exp vars: 30, dual exp vars: 15
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scaling: 1
	  max_iters: 1000, normalize: 1, warm_start: 0
lin-sys:  sparse-direct
	  nnz(A): 162, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.94e+01  9.22e+00  1.71e+02 -1.49e+02  1.00e-01  1.73e-04
   225| 7.46e-06  1.69e-04  2.12e-04  1.49e+01  4.67e+00  1.77e-02
------------------------------------------------------------------
status:  solved
timings: total: 1.81e-02s = setup: 3.32e-04s + solve: 1.78e-02s
	 lin-sys: 3.40e-04s, cones: 1.71e-02s, accel: 5.92e-06s
lin-sys: nnz(L): 415
------------------------------------------------------------------
cones: dist(s, K) = 0.00e+00, dist(y, K*) = 0.00e+00
comp slack: s'y/|s||y| = -4.15e-11, gap: |x'Px+c'x+b'y| = 2.12e-04
pri res: |Ax+s-b| = 7.46e-06, dua res: |Px+A'y+c| = 1.69e-04
------------------------------------------------------------------
objective = 14.901001
------------------------------------------------------------------
```

**Comment by bodono** [comment]
Same for the SDP instance:
```
------------------------------------------------------------------
	       SCS v3.0.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 15, constraints m: 46
cones: 	  f: primal zero / dual free vars: 3
	  l: linear vars: 3
	  q: soc vars: 9, soc blks: 3
	  s: sd vars: 19, sd blks: 3
	  e: exp vars: 6, dual exp vars: 6
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scaling: 1
	  max_iters: 1000, normalize: 1, warm_start: 0
lin-sys:  sparse-direct
	  nnz(A): 66, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.58e+01  6.74e+00  2.72e+02 -2.90e+02  1.00e-01  5.48e-04
   250| 7.26e-04  7.93e-05  5.52e-04 -1.02e+01  7.60e-01  8.21e-03
   275| 6.48e-04  6.93e-05  5.12e-04 -1.02e+01  7.60e-01  8.89e-03
------------------------------------------------------------------
status:  solved
timings: total: 9.14e-03s = setup: 2.40e-04s + solve: 8.90e-03s
	 lin-sys: 2.27e-04s, cones: 8.40e-03s, accel: 7.97e-06s
lin-sys: nnz(L): 154
------------------------------------------------------------------
cones: dist(s, K) = 1.56e-07, dist(y, K*) = 2.33e-10
comp slack: s'y/|s||y| = 4.87e-11, gap: |x'Px+c'x+b'y| = 5.12e-04
pri res: |Ax+s-b| = 6.48e-04, dua res: |Px+A'y+c| = 6.93e-05
------------------------------------------------------------------
objective = -10.242564
------------------------------------------------------------------

```

**Comment by kalmarek** [comment]
@bodono thanks for checking this! I suspected something off in the wrapper, now we know it for sure :)

**Comment by kalmarek** [comment]
@bodono Indeed, with `8bfba8c66cefa1db42998e1d52bd7417b62a6d63` exp and sdp cone examples run just fine! (I compile my scs with openmp using [this script](https://gist.github.com/kalmarek/1ddc06f2d76f6b6c343bf7cb9be98d75))

Just to double check a few things:
1. When you run those examples in python what is `bu`, `bl`, and `bsize`?
here I say `bu == bl == Float64[]` (empty array) and `bsize = 0`. But then I read in the comments 
https://github.com/cvxgrp/scs/blob/8bfba8c66cefa1db42998e1d52bd7417b62a6d63/include/scs.h#L75
which means that `bsize` should be `1`?! Note that if I make this change scs fails validation phase telling me:
```
WARN: A->p (column pointers) not strictly increasing, column 1 empty
cone dimensions 29 not equal to num rows in A = m = 28
cone validation error
ERROR: Validation returned failure
```

2. How is `P` initialized? I initialize `P` to be
```
    P: SCSMatrix{Int64}
      values: Ptr{Float64} @0x00007f66952a8fa0 # pointer to Float64[] (length: 0)
      rowval: Ptr{Int64} @0x00007f66952a9040 # pointer to Int64[] (length: 0)
      colptr: Ptr{Int64} @0x00007f6622206970 # pointer to Int64[0,...,0] (length: n+1)
      m: Int64 n
      n: Int64 n
```
Is that correct? Who should own memory in `P`?

**Comment by bodono** [comment]
Yes I need to write / correct the documentation.

If bu / bl are empty then bsize=0. Their length determines bsize rather than the other way around. The current formula is bsize = {0 if len(bu) == 0; else len(bu) + 1}. Thinking about it now I might switch to `bsize = len(bu)`, what do you think?

P should be passed in as a compressed sparse column *upper triangular* matrix (the same format as A other than the upper triangular requirement). If P is empty then you can just pass NULL. If it is not upper triangular SCS tries it's best to work anyway but I haven't tested it so it might break. The caller owns the memory for P.

**Comment by bodono** [comment]
I just updated bsize to be bsize = len(bu) = len(bl), which is simpler for the user I think.

**Comment by kalmarek** [comment]
@bodono thanks for the comments! I have updated the pull here accordingly :)
----

@odow, @blegat I made a decision not to export `scs_(init|solve|finish|version)`, which seemed a little weird to me, but I'm not so sure about it, please chime in if you have an opinion.

finally I spotted an issue, where we accept `A` (and now also `P`) as `VecOrMatOrSparse`, but no methods are implemented for creating `ManagedSCSMatrix` from `AbstractVector`s -- I guess that nobody actually used this. This prompts me to remove `Vec` part here.

**Comment by bodono** [comment]
I reverted the change to the `bsize` to be the full length of the cone (ie, `bsize = len(bu) + 1 = len(bl) + 1`), to be more consistent and have more intuitive behavior when `bsize=1`.

The cones are now explained here: https://www.cvxgrp.org/scs/api/cones.html

**Comment by bodono** [comment]
The 3.0 PR is here and is basically ready to be merged: cvxgrp/scs#169

**Comment by kalmarek** [comment]
@bodono, thanks. It will take me at least a couple of days to find time to have a look into updating this pull, so sorry if this is holding you back.

**Comment by bodono** [comment]
There's no rush! Whenever you have time is fine!

**Comment by odow** [comment]
I've made a number of large breaking changes to SCS.jl since this PR was opened, so the easiest path forward is probably a new pull request. It should be relatively trivial to do so though. 

The main blocker is a 3.0 tag of CVX so we can compile binaries.

@bodono can I make a 3.0 build off https://github.com/cvxgrp/scs/commit/1a7c3bfde650b710e71f2bb7e362bb1ecfd4e4fb? Or are there more changes planned?

**Comment by kalmarek** [comment]
@odow indeed the best way is probably to start anew;

but I think tagging a new version (`0.8`) without updating to `scs-3.0` is also sensible as it givies users easy way of using `scs-2.*` with the brand new MOI ;)

**Comment by kalmarek** [comment]
closing in favour of #221

**Pull request closed without merging**
