### PR TITLE
Add buildkite CI for GPU

### LINKED ISSUE #201: Update GPU CI
https://discourse.julialang.org/t/juliagpu-ci-moving-to-buildkite/49925

### PR DESCRIPTION
**Pull request by odow**
Closes #201 

TODO: Complete steps https://github.com/JuliaGPU/buildkite#adding-a-repository

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5

Also TODO:

- [x] Remove `.gitlab-ci.yml`

### CODE REVIEW

**Comment by odow** [comment]
So I can kick off builds manually: https://buildkite.com/julialang/scs-dot-jl/builds

But I can't seem to get the webhook to work. It fires and gets a `200` response, but a build isn't triggered. 

@maleadt are we missing some settings on the buildkite side?

**Comment by maleadt** [comment]
I'm still working out the status update thing; turns out you need an admin at both sides to use the integration, and I'd rather have a way without that.

**Comment by odow** [comment]
Okay. Let me know what help I can provide from our end.

**Comment by kalmarek** [comment]
@odow as per slack conversation @maleadt or @dilumaluthge need to become an admin of the github jump-dev org temporarily, so they can set it up properly; they can be demoted to standard members afterwards.

**Comment by odow** [comment]
Oops, I don't check slack often. 

I've sent @maleadt an invite to become an Owner of `jump-dev`. He already had Admin access to `SCS.jl`.

**Comment by maleadt** [comment]
Thanks, the integration can be set up. You can remove me as an owner again. And as you can see, that fixed the status pushes: I restarted the build, and it appears here now.

**Comment by maleadt** [comment]
You will want to switch to the v1 plugins and add a timeout, see the template in https://github.com/JuliaGPU/buildkite

**Comment by odow** [comment]
Looks like this worked. @kalmarek merge if you're happy.

**Pull request merged**
