### PR TITLE
add SCS_GPU_jll

### PR DESCRIPTION
**Pull request by kalmarek**
this is a first try to add the GPU solver through BinaryBuilder architecture;

Since SCS is really tiny we don't depend on (huge!) `CUDA_jll`, but just rely on the runtime `libcuda.so` detection;

(this solution was suggested by @maleadt in https://github.com/JuliaPackaging/Yggdrasil/pull/1294#issuecomment-656121033)

If you have CUDA enabled hardware please test and comment

### CODE REVIEW

**Comment by maleadt** [comment]
You can use the JuliaGPU CI: https://github.com/JuliaGPU/gitlab-ci

**Comment by kalmarek** [comment]
tbh I couldn't come up with something better than
```julia
using CUDA_jll # optional, to load the correct libcublas.so
using SCS
SCS.eval(:(
    import SCS_GPU_jll;
    const gpuindirect = SCS_GPU_jll.libscsgpuindir;
    GpuIndirectSolver in available_solvers || push!(available_solvers, GpuIndirectSolver);
    include("src/c_wrapper.jl"); # to @eval the ccalls depending on gpuindirect 
    ))
```
this is hacky, but also not automatic so I'd deem it ok to include in README. what do you think @blegat @mlubin ?

**Comment by kalmarek** [comment]
at the moment build is failing since I checked in Manifest.toml for you (people with Nvidia Gpus) to try it out @blegat @odow @juan-pablo-vielma could you test it?
```julia
using CUDA_jll
using SCS
include("test/runtests.jl")
```
you should be able to see
```
---------------------------------------------------------------------------- 
        SCS v2.1.2 - Splitting Conic Solver                                                    
        (c) Brendan O'Donoghue, Stanford University, 2012                   
----------------------------------------------------------------------------                   
Lin-sys: sparse-indirect GPU, nnz in A = 66, CG tol ~ 1/iter^(2.00)
```
and see results for tests for the `GpuIndirectSolver`.

**Comment by odow** [comment]
What about setting up the JuliaGPU CI?

**Comment by kalmarek** [comment]
@odow I'll try to do it when SCS_GPU_jll is available in the Registry

**Comment by odow** [comment]
I requested access.

**Comment by kalmarek** [comment]
@odow the access was granted, but it seems that you need to do this...

**Comment by kalmarek** [comment]
@odow what is the status of this?

**Comment by odow** [comment]
No progress. I won't get a chance to look at this until next week at the earliest.

**Comment by kalmarek** [comment]
ok, just let me know if you need some input from me

**Comment by kalmarek** [comment]
superseded by #198

**Pull request closed without merging**
