### PR TITLE
WIP: Add precompilation directives

### PR DESCRIPTION
**Pull request by odow**
See https://github.com/jump-dev/JuMP.jl/pull/2484

### CODE REVIEW

**Comment by kalmarek** [comment]
I tried this but I get solution with nans:
```julia
julia> module Foo

       using JuMP
       #using Ipopt
       using SCS
       #using GLPK

       function stress_precompile()
           input_dir =
               joinpath(dirname(dirname(pathof(JuMP))), "docs", "src", "examples")
           for (root, dirs, files) in walkdir(input_dir)
               for file in files
                   if !endswith(file, ".jl")
                       continue
                   end
                   include(joinpath(root, file))
               end
           end
           return
       end

       function example_diet()
           categories = ["calories", "protein", "fat", "sodium"]
           category_data = Containers.DenseAxisArray([
               1800 2200;
               91   Inf;
               0    65;
               0    1779
               ], categories, ["min", "max"]
           )
           foods = [
               "hamburger", "chicken", "hot dog", "fries", "macaroni", "pizza",
               "salad", "milk", "ice cream",
           ]
           cost = Containers.DenseAxisArray(
               [2.49, 2.89, 1.50, 1.89, 2.09, 1.99, 2.49, 0.89, 1.59],
               foods
           )
           food_data = Containers.DenseAxisArray(
               [
                   410 24 26 730;
                   420 32 10 1190;
                   560 20 32 1800;
                   380  4 19 270;
                   320 12 10 930;
                   320 15 12 820;
                   320 31 12 1230;
                   100  8 2.5 125;
                   330  8 10 180
               ], foods, categories
           )
           model = Model(SCS.Optimizer)
           @variables(model, begin
               category_data[c, "min"] <= nutrition[c = categories] <= category_data[c, "max"]
               buy[foods] >= 0
           end)
           @objective(model, Min, sum(cost[f] * buy[f] for f in foods))
           @constraint(model, [c in categories],
               sum(food_data[f, c] * buy[f] for f in foods) == nutrition[c]
           )
           optimize!(model)
           term_status = termination_status(model)
           @assert term_status == MOI.OPTIMAL
           @constraint(model, buy["milk"] + buy["ice cream"] <= 6)
           optimize!(model)
           @assert termination_status(model) == MOI.INFEASIBLE
           @assert primal_status(model) == MOI.NO_SOLUTION
           return
       end

       end

julia> @time Foo.example_diet()
----------------------------------------------------------------------------
        SCS v2.1.2 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 57, CG tol ~ 1/iter^(2.00)
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 13, constraints m = 21
Cones:  primal zero / dual free vars: 4
        linear vars: 17
Setup time: 7.19e-05s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      nan       nan       nan       nan      -nan       nan  2.69e-05 
   100|      nan       nan       nan       nan      -nan       nan  1.19e-03 
   200|      nan       nan       nan       nan      -nan       nan  2.40e-03 
   300|      nan       nan       nan       nan      -nan       nan  3.58e-03 
   400|      nan       nan       nan       nan      -nan       nan  4.74e-03 
   500|      nan       nan       nan       nan      -nan       nan  6.03e-03 
   600|      nan       nan       nan       nan      -nan       nan  7.23e-03 
   700|      nan       nan       nan       nan      -nan       nan  8.43e-03 
   800|      nan       nan       nan       nan      -nan       nan  9.58e-03 
   900|      nan       nan       nan       nan      -nan       nan  1.08e-02 
  1000|      nan       nan       nan       nan      -nan       nan  1.20e-02 
  1100|      nan       nan       nan       nan      -nan       nan  1.32e-02 
  1200|      nan       nan       nan       nan      -nan       nan  1.44e-02 
  1300|      nan       nan       nan       nan      -nan       nan  1.56e-02 
  1400|      nan       nan       nan       nan      -nan       nan  1.68e-02 
  1500|      nan       nan       nan       nan      -nan       nan  1.82e-02 
  1600|      nan       nan       nan       nan      -nan       nan  1.98e-02 
  1700|      nan       nan       nan       nan      -nan       nan  2.11e-02 
  1800|      nan       nan       nan       nan      -nan       nan  2.27e-02 
  1900|      nan       nan       nan       nan      -nan       nan  2.39e-02 
  2000|      nan       nan       nan       nan      -nan       nan  2.51e-02 
  2100|      nan       nan       nan       nan      -nan       nan  2.63e-02 
  2200|      nan       nan       nan       nan      -nan       nan  2.75e-02 
  2300|      nan       nan       nan       nan      -nan       nan  2.89e-02 
  2400|      nan       nan       nan       nan      -nan       nan  3.01e-02 
  2500|      nan       nan       nan       nan      -nan       nan  3.12e-02 
  2600|      nan       nan       nan       nan      -nan       nan  3.25e-02 
  2700|      nan       nan       nan       nan      -nan       nan  3.40e-02 
  2800|      nan       nan       nan       nan      -nan       nan  3.54e-02 
  2900|      nan       nan       nan       nan      -nan       nan  3.66e-02 
  3000|      nan       nan       nan       nan      -nan       nan  3.78e-02 
  3100|      nan       nan       nan       nan      -nan       nan  3.90e-02 
  3200|      nan       nan       nan       nan      -nan       nan  4.02e-02 
  3300|      nan       nan       nan       nan      -nan       nan  4.14e-02 
  3400|      nan       nan       nan       nan      -nan       nan  4.26e-02 
  3500|      nan       nan       nan       nan      -nan       nan  4.38e-02 
  3600|      nan       nan       nan       nan      -nan       nan  4.49e-02 
  3700|      nan       nan       nan       nan      -nan       nan  4.63e-02 
  3800|      nan       nan       nan       nan      -nan       nan  4.76e-02 
  3900|      nan       nan       nan       nan      -nan       nan  4.88e-02 
  4000|      nan       nan       nan       nan      -nan       nan  5.00e-02 
  4100|      nan       nan       nan       nan      -nan       nan  5.13e-02 
  4200|      nan       nan       nan       nan      -nan       nan  5.26e-02 
  4300|      nan       nan       nan       nan      -nan       nan  5.42e-02 
  4400|      nan       nan       nan       nan      -nan       nan  5.60e-02 
  4500|      nan       nan       nan       nan      -nan       nan  5.76e-02 
  4600|      nan       nan       nan       nan      -nan       nan  5.92e-02 
  4700|      nan       nan       nan       nan      -nan       nan  6.07e-02 
  4800|      nan       nan       nan       nan      -nan       nan  6.20e-02 
  4900|      nan       nan       nan       nan      -nan       nan  6.32e-02 
  5000|      nan       nan       nan       nan      -nan       nan  6.44e-02 
----------------------------------------------------------------------------
Status: Unbounded/Inaccurate
Hit max_iters, solution may be inaccurate, returning best found solution.
Timing: Solve time: 6.44e-02s
        Lin-sys: avg # CG iterations: 13.00, avg solve time: 4.05e-06s
        Cones: avg projection time: 5.09e-08s
        Acceleration: avg step time: 7.79e-06s
----------------------------------------------------------------------------
Certificate of dual infeasibility:
dist(s, K) = 0.0000e+00
|Ax + s|_2 * |c|_2 = nan
c'x = nan
============================================================================
ERROR: AssertionError: term_status == MOI.OPTIMAL
Stacktrace:
 [1] example_diet()
   @ Main.Foo ./REPL[6]:63
 [2] top-level scope
   @ ./timing.jl:206 [inlined]
 [3] top-level scope
   @ ./REPL[7]:0

julia> 
```

**Comment by odow** [comment]
Did you try this normally without the precompiles?

**Comment by mlubin** [comment]
I'm guessing the NaNs are coming from the `Inf` variable upper bound: https://github.com/jump-dev/SCS.jl/issues/170

**Comment by kalmarek** [comment]
Indeed they are; changing the `Inf` to `1e+6` I get
```julia
ERROR: LoadError: AssertionError: primal_status(model) == MOI.NO_SOLUTION
```

**Comment by odow** [comment]
Closing as stale. Will revisit at a later date.

**Pull request closed without merging**
